// <auto-generated />
using System;
using IntelliSoftAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntelliSoftAPIV2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250809234117_ReconfigureCotizacion")]
    partial class ReconfigureCotizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCatalogoUnidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_unidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre");

                    b.Property<string>("Simbolo")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("simbolo");

                    b.HasKey("IdUnidad")
                        .HasName("PK__TB_Catal__95D7C92B47769009");

                    b.ToTable("TB_CatalogoUnidad", "catalogos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbComentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comentario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<int>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("mensaje");

                    b.Property<int>("OpinionId")
                        .HasColumnType("int")
                        .HasColumnName("opinion_id");

                    b.HasKey("IdComentario")
                        .HasName("PK__TB_Comen__1BA6C6F42BCD59A9");

                    b.HasIndex("OpinionId");

                    b.ToTable("TB_Comentarios", "seguridad");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCompra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<string>("ClaveCompra")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("clave_compra");

                    b.Property<int?>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("FechaCompra")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_compra");

                    b.Property<string>("Observacion")
                        .HasMaxLength(65)
                        .IsUnicode(false)
                        .HasColumnType("varchar(65)")
                        .HasColumnName("observacion");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    b.HasKey("IdCompra")
                        .HasName("PK__TB_Compr__C4BAA604B65F62CC");

                    b.HasIndex("ProveedorId");

                    b.ToTable("TB_Compra", "almacen");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCompraDetalle", b =>
                {
                    b.Property<int>("IdCompraDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compra_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompraDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("compra_id");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("precio_unitario");

                    b.Property<string>("Presentacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("presentacion");

                    b.HasKey("IdCompraDetalle")
                        .HasName("PK__TB_Compr__C08AA00690F89481");

                    b.HasIndex("CompraId");

                    b.HasIndex("InsumoId");

                    b.ToTable("TB_CompraDetalle", "almacen");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCotizacion", b =>
                {
                    b.Property<int>("IdCotizaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cotizaciones");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCotizaciones"));

                    b.Property<string>("ClaveCotizacion")
                        .HasMaxLength(65)
                        .HasColumnType("nvarchar(65)")
                        .HasColumnName("clave_cotizacion");

                    b.Property<string>("DetalleCotizacion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("detalle_cotizacion");

                    b.Property<int>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_solicitud");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("cliente_id");

                    b.HasKey("IdCotizaciones")
                        .HasName("PK__TB_Cotiz__21B35BCEDB402AE2");

                    b.HasIndex("ClaveCotizacion")
                        .IsUnique()
                        .HasFilter("[clave_cotizacion] IS NOT NULL");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_Cotizaciones", "operaciones");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbInsumo", b =>
                {
                    b.Property<int>("IdInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_insumo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInsumo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre");

                    b.Property<int>("UnidadId")
                        .HasColumnType("int")
                        .HasColumnName("unidad_id");

                    b.HasKey("IdInsumo")
                        .HasName("PK__TB_Insum__D4F202B1F9356D73");

                    b.HasIndex("UnidadId");

                    b.ToTable("TB_Insumo", "catalogos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbInventarioInsumo", b =>
                {
                    b.Property<int>("IdInventarioInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_inventario_insumo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventarioInsumo"));

                    b.Property<int?>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("compra_id");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("costo");

                    b.Property<decimal?>("Debe")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("debe");

                    b.Property<int?>("Entrada")
                        .HasColumnType("int")
                        .HasColumnName("entrada");

                    b.Property<int?>("Existencias")
                        .HasColumnType("int")
                        .HasColumnName("existencias");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<decimal?>("Haber")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("haber");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int")
                        .HasColumnName("insumo_id");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("int")
                        .HasColumnName("pedido_id");

                    b.Property<decimal?>("Promedio")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("promedio");

                    b.Property<decimal?>("Saldo")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("saldo");

                    b.Property<int?>("Salida")
                        .HasColumnType("int")
                        .HasColumnName("salida");

                    b.HasKey("IdInventarioInsumo")
                        .HasName("PK__TB_Inven__D64F6112270E14D6");

                    b.HasIndex("CompraId");

                    b.HasIndex("InsumoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("TB_InventarioInsumo", "almacen");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbOpinion", b =>
                {
                    b.Property<int>("IdOpinion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_opinion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOpinion"));

                    b.Property<int?>("Calificacion")
                        .HasColumnType("int")
                        .HasColumnName("calificacion");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("comentario");

                    b.Property<int>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("cliente_id");

                    b.HasKey("IdOpinion")
                        .HasName("PK__TB_Opini__04DDBD783B2ACCAE");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_Opiniones", "operaciones");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbPedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pedido");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int")
                        .HasColumnName("cotizacion_id");

                    b.Property<int>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("FechaPedido")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_pedido");

                    b.HasKey("IdPedido")
                        .HasName("PK__TB_Pedid__6FF01489CC0F52C0");

                    b.HasIndex("CotizacionId");

                    b.ToTable("TB_Pedido", "operaciones");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbProducto", b =>
                {
                    b.Property<int>("IdProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_productos");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductos"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estatus")
                        .HasColumnType("int")
                        .HasColumnName("estatus");

                    b.Property<decimal?>("HectareaBase")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("hectarea_base");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PorcentajeGanancia")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_ganancia");

                    b.Property<decimal>("PorcentajeRiesgo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_riesgo");

                    b.HasKey("IdProductos")
                        .HasName("PK__TB_Produ__3804F4FB0336751E");

                    b.ToTable("TB_Productos", "catalogos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbProductoInsumo", b =>
                {
                    b.Property<int>("IdProductoInsumo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto_insumo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoInsumo"));

                    b.Property<decimal?>("Cantidad")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("cantidad");

                    b.Property<int?>("InsumoId")
                        .HasColumnType("int")
                        .HasColumnName("insumo_id");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.HasKey("IdProductoInsumo")
                        .HasName("PK__TB_Produ__E26856CC7C46A71C");

                    b.HasIndex("InsumoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("TB_ProductoInsumo", "catalogos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbProveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contacto");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("correo_electronico");

                    b.Property<string>("DescripcionServicio")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion_servicio");

                    b.Property<int>("Estatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("estatus");

                    b.Property<string>("Nombre")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor")
                        .HasName("PK__TB_Prove__8D3DFE28F215D3E6");

                    b.ToTable("TB_Proveedor", "catalogos");
                });

            modelBuilder.Entity("IntelliSoftAPIV2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContrasenaGenerada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contrasena_generada");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("estatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fecha_registro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("IntelliSoftAPIV2.Models.TbCotizacionProductoDetalle", b =>
                {
                    b.Property<int>("IdCotizacionProductoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cotizacion_producto_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCotizacionProductoDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("cantidad");

                    b.Property<int>("CotizacionProductoId")
                        .HasColumnType("int")
                        .HasColumnName("cotizacion_producto_id");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("PrecioPromedio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_promedio");

                    b.HasKey("IdCotizacionProductoDetalle")
                        .HasName("PK_TB_CotizacionProductoDetalle");

                    b.HasIndex("CotizacionProductoId");

                    b.HasIndex("InsumoId");

                    b.ToTable("TB_CotizacionProductoDetalle", "operaciones");
                });

            modelBuilder.Entity("IntelliSoftAPIV2.Models.TbDocumento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<int>("IdProductos")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("nombre_columna");

                    b.Property<int?>("ProductoIdProductos")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("IdDocumento")
                        .HasName("PK_TB_Documento_IdDocumento");

                    b.HasIndex("ProductoIdProductos");

                    b.ToTable("TB_Documento", "catalogos");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TbCotizacionProducto", b =>
                {
                    b.Property<int>("IdCotizacionProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cotizacion_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCotizacionProducto"));

                    b.Property<int>("AplicaRiesgo")
                        .HasColumnType("int")
                        .HasColumnName("aplica_riesgo");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int")
                        .HasColumnName("cotizacion_id");

                    b.Property<decimal>("Hectareas")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("hectareas");

                    b.Property<decimal>("PorcentajeGanancia")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_ganancia");

                    b.Property<decimal>("PorcentajeRiesgo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_riesgo");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.HasKey("IdCotizacionProducto")
                        .HasName("PK_TB_CotizacionProducto");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("TB_CotizacionProducto", "operaciones");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbComentario", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbOpinion", "Opinion")
                        .WithMany("Comentarios")
                        .HasForeignKey("OpinionId")
                        .IsRequired()
                        .HasConstraintName("FK_Comentario_Opinion");

                    b.Navigation("Opinion");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCompra", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbProveedor", "Proveedor")
                        .WithMany("TbCompras")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK__TB_Compra__prove__7F2BE32F");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCompraDetalle", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbCompra", "Compra")
                        .WithMany("TbCompraDetalles")
                        .HasForeignKey("CompraId")
                        .IsRequired()
                        .HasConstraintName("FK__TB_Compra__compr__7D439ABD");

                    b.HasOne("IntelliSoftAPI.Models.TbInsumo", "Insumo")
                        .WithMany("TbCompraDetalles")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK__TB_Compra__insum__7E37BEF6");

                    b.Navigation("Compra");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCotizacion", b =>
                {
                    b.HasOne("IntelliSoftAPIV2.Models.ApplicationUser", "Usuario")
                        .WithMany("TbCotizaciones")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__TB_Cotiza__clien__07C12930");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbInsumo", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbCatalogoUnidad", "Unidad")
                        .WithMany("TbInsumos")
                        .HasForeignKey("UnidadId")
                        .IsRequired()
                        .HasConstraintName("FK__TB_Insumo__unida__02FC7413");

                    b.Navigation("Unidad");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbInventarioInsumo", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbCompra", "Compra")
                        .WithMany("TbInventarioInsumos")
                        .HasForeignKey("CompraId")
                        .HasConstraintName("FK__TB_Invent__compr__01142BA1");

                    b.HasOne("IntelliSoftAPI.Models.TbInsumo", "Insumo")
                        .WithMany("TbInventarioInsumos")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK__TB_Invent__insum__02084FDA");

                    b.HasOne("IntelliSoftAPI.Models.TbPedido", "Pedido")
                        .WithMany("TbInventarioInsumos")
                        .HasForeignKey("PedidoId")
                        .HasConstraintName("FK__TB_Invent__pedid__00200768");

                    b.Navigation("Compra");

                    b.Navigation("Insumo");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbOpinion", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbProducto", "Producto")
                        .WithMany("TbOpiniones")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__TB_Opinio__produ__08B54D69");

                    b.HasOne("IntelliSoftAPIV2.Models.ApplicationUser", "Usuario")
                        .WithMany("TbOpiniones")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__TB_Opinio__clien__09A971A2");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbPedido", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbCotizacion", "Cotizacion")
                        .WithMany("TbPedidos")
                        .HasForeignKey("CotizacionId")
                        .IsRequired()
                        .HasConstraintName("FK_TB_Pedido_Cotizacion");

                    b.Navigation("Cotizacion");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbProductoInsumo", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbInsumo", "Insumo")
                        .WithMany("TbProductoInsumos")
                        .HasForeignKey("InsumoId")
                        .HasConstraintName("FK__TB_Produc__insum__03F0984C");

                    b.HasOne("IntelliSoftAPI.Models.TbProducto", "Producto")
                        .WithMany("TbProductoInsumos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__TB_Produc__produ__04E4BC85");

                    b.Navigation("Insumo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("IntelliSoftAPIV2.Models.TbCotizacionProductoDetalle", b =>
                {
                    b.HasOne("TbCotizacionProducto", "CotizacionProducto")
                        .WithMany("Detalles")
                        .HasForeignKey("CotizacionProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliSoftAPI.Models.TbInsumo", "Insumo")
                        .WithMany("TbCotizacionProductoDetalles")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK_CotizacionProductoDetalle_Insumo");

                    b.Navigation("CotizacionProducto");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("IntelliSoftAPIV2.Models.TbDocumento", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbProducto", "Producto")
                        .WithMany("TbDocumentos")
                        .HasForeignKey("ProductoIdProductos");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("IntelliSoftAPIV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("IntelliSoftAPIV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliSoftAPIV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("IntelliSoftAPIV2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TbCotizacionProducto", b =>
                {
                    b.HasOne("IntelliSoftAPI.Models.TbCotizacion", "Cotizacion")
                        .WithMany("CotizacionProductos")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IntelliSoftAPI.Models.TbProducto", "Producto")
                        .WithMany("TbCotizacionProductos")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK_CotizacionProducto_Producto");

                    b.Navigation("Cotizacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCatalogoUnidad", b =>
                {
                    b.Navigation("TbInsumos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCompra", b =>
                {
                    b.Navigation("TbCompraDetalles");

                    b.Navigation("TbInventarioInsumos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbCotizacion", b =>
                {
                    b.Navigation("CotizacionProductos");

                    b.Navigation("TbPedidos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbInsumo", b =>
                {
                    b.Navigation("TbCompraDetalles");

                    b.Navigation("TbCotizacionProductoDetalles");

                    b.Navigation("TbInventarioInsumos");

                    b.Navigation("TbProductoInsumos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbOpinion", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbPedido", b =>
                {
                    b.Navigation("TbInventarioInsumos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbProducto", b =>
                {
                    b.Navigation("TbCotizacionProductos");

                    b.Navigation("TbDocumentos");

                    b.Navigation("TbOpiniones");

                    b.Navigation("TbProductoInsumos");
                });

            modelBuilder.Entity("IntelliSoftAPI.Models.TbProveedor", b =>
                {
                    b.Navigation("TbCompras");
                });

            modelBuilder.Entity("IntelliSoftAPIV2.Models.ApplicationUser", b =>
                {
                    b.Navigation("TbCotizaciones");

                    b.Navigation("TbOpiniones");
                });

            modelBuilder.Entity("TbCotizacionProducto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
